#!/bin/bash

#creating variables for path to custom docker log files
export DOCKER_BE_LOG="/home/seed/Documents/lab-content/team-network/docker-be.log"
export DOCKER_FE_LOG="/home/seed/Documents/lab-content/team-network/docker-fe.log"

#navigate to project network folder, ensure dependencies,
#then clean up existing logs and docker output
cd ~/Documents/lab-content
source development.env
cd team-network
rm -r output_new
rm -f docker-be.log
rm -f docker-fe.log
touch docker-be.log
touch docker-fe.log

#minimize all terminals then open lab guide
gnome-terminal --tab -- bash -c 'for window in $(xdotool search --onlyvisible --class ".*"); do xdotool windowminimize "$window"; done; okular ~/Documents/lab-content/lab-guides/bgp-attack-lab-guide.pdf'

#compile python script to start process of building network
python3 ./netBuild.py

#move to output folder generated by python script
#make sure potentially existing docker network is removed and reset
#then build and start up desired network redirecting output to log
sleep 3
cd output_new
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
yes | docker network prune

#navigate to client folder in a new terminal
#then build and start up front end internet visualizer
gnome-terminal --tab -- bash -c "\
cd ~/Documents/lab-content/client; \
export COMPOSE_HTTP_TIMEOUT=200; \
docker-compose build; \
docker-compose down; \
docker-compose up > "$DOCKER_FE_LOG" 2>&1; \
exec bash" &

sleep 3

#loop until flag showing backend is ready shows up in log
#then open browser to display internet emulator
gnome-terminal --tab -- bash -c "\
while ! grep -q 'bird: Started' "$DOCKER_BE_LOG"; do \
        sleep 5; \
done; \
firefox http://127.0.0.1:8080/map.html; \
wmctrl -r "Mozilla Firefox" -e 0,0,0,960,1080; \
exec bash"

#latency issues can cause timeout error with docker 
export COMPOSE_HTTP_TIMEOUT=200
docker-compose build
docker-compose up > "$DOCKER_BE_LOG" 2>&1


